---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name:  ubuntu/trusty64

suites:
  - name: default
    run_list:
      - recipe[java]
      - recipe[tvarit-cookbook::default]
    attributes:
